# JavaCafe01 Prompt

format = "$all"
add_newline = true

[character]
error_symbol = "[](bold red)"
success_symbol = "[](bold green)"
vicmd_symbol = "[](bold yellow)"
format = "$symbol [|](bold bright-black) "

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[directory]
disabled = true

[line_break]
disabled = true

[lua]
symbol = "[](blue) "

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count}"
behind = "🐢 ×${count}"
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "🛤️  ×${count}"
stashed = "📦 "
modified = "📝 ×${count}"
staged = "🗃️  ×${count}"
renamed = "📛 ×${count}"
deleted = "🗑️  ×${count}"
style = "bright-white"
format = "$all_status$ahead_behind "